### ISSUE TITLE
isParaunitary can handle IIR filters?

### ISSUE THREAD

**Issue by orchidas** [SebastianJiroSchlecht/fdnToolbox#2]
Hi Sebastian,I was taking a look at the isParaunitary.m file, and I am wondering if it can handle IIR filters in the matrix A? This means that the matrix will have a set of numerators and a set of denominators, each of size (n, n, order).

**Comment by SebastianJiroSchlecht** [comment]
Hi Orchi,
no, the IIR filters are not supported. And I believe that it would take some more intricate work to get this right. However, if you take the impulse response of each filter as an FIR, then you should still get a very good approximation (at least numerically).

**Comment by orchidas** [comment]
Thanks Sebastian. The solution is not evidently apparent to me either - probably doable, but not trivial.
