### ISSUE TITLE
decayFitNet2InitialLevel

### ISSUE THREAD

**Issue by orchidas** [SebastianJiroSchlecht/fdnToolbox#3]
Hi Sebastian, I had a question about this function used in `examples/RIR2FDN`. Is this trying to match the initial gain of the EDC? i.e, for frequency band f, is it matching $A_f$?
$EDC_f(t) = A_f \exp(-t/ \tau_f) + N_f$
It would be great if you could discuss what the function is doing. It's adding it as a GEQ to the output filters - why not include it within the delay line filters? 
If it's coming out in a paper, I can wait till it a preprint gets published :)

**Comment by SebastianJiroSchlecht** [comment]
Hi Orchi,
yes, this is the idea. In principle, there is nothing new compared to the original Jot paper. However, in the general case of GEQ the computation needs some more care. 

If the GEQ would be included with the delay line filters also the T60 would change. There needs to be two independent sets of equalizers for the initial gain and decay.
